### ISSUE TITLE
Not Working Blender 2.93.1

### ISSUE THREAD

**Issue by Ayusman-Singhal** [nalexandru/api-ms-win-core-path-HACK#2]
Please post a video tutorial...........
Please

**Comment by nalexandru** [comment]
I don't understand what to make a video of, all you have to do is copy a file to System32 or Blender's directory.
What i can do is add the DLL to the 2.93.1 release zip file, all you have to do is extract it and run blender.exe.

2.93.1 modified zip: https://1drv.ms/u/s!AhpnXywMA4U1mQy8_ukTjKGTsfqt?e=7IawBZ
