### ISSUE TITLE
Github page description update

### ISSUE THREAD

**Issue by Illasera** [nalexandru/api-ms-win-core-path-HACK#8]
In "Code" tab, Requesting to change the description line from: 

"For Blender 3.0, see https://github.com/nalexandru/BlenderCompat"

to

"For Blender 3.0 and above, see : https://github.com/nalexandru/BlenderCompat"
OR
"For versions more up-to-date than 2.93 , see : https://github.com/nalexandru/BlenderCompat"

*Currently, people who read the given description may think "blendercompat" only applies to version 3.0 while it works on higher versions as well (For the moment).

** BlenderCompat project's code page also need updates to let users know it support higher versions than 3.0 as well, I can open an issue ticket there but its a small job to change it over there as well so i will keep it under 1 issue here.

**Comment by lorand-horvath** [comment]
@Illasera You should do a PR...

**Comment by nalexandru** [comment]
I've updated the readme as you suggested.
